services:
  - type: static
    name: Deal Scarper Frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    autoDeployTrigger: commit

  - type: web
    name: Deal Scarper Backend
    env: docker
    plan: starter
    region: oregon
    autoDeployTrigger: commit
    envVars:
      - key: MONGO_URI
        fromService:
          type: pserv
          name: deal-scraper-mongodb
          property: connectionString

  - type: worker
    name: Deal Scraper (Web Scraper)
    env: python 
    buildCommand: cd scrapper && pip install -r requirements.txt
    startCommand: cd scrapper && python3 main.py
    autoDeployTrigger: commit
    envVars:
      - key: MONGO_URI
        fromService:
          type: pserv
          name: deal-scraper-mongodb
          property: connectionString

  - type: pserv
    name: deal-scraper-mongodb
    env: docker
    plan: starter
    repo: https://github.com/kreuzwerker/terraform-provider-docker
    region: oregon
