spring.application.name=Deal_Scrapper
spring.mongodb.uri=mongodb+srv://Backup_User:subashsg7777_db_user@cluster0.a0nrawg.mongodb.net/?appName=Cluster0
spring.mongodb.database=deal_scrapper
server.port=8080