name: Backend CI

on:
  pull_request:
    branches: [ pipeline_workflow ]
    paths:
      - 'backend/**'
  push:
    branches: [ pipeline_workflow ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Backend Unit Tests
        run: |
          cd backend/Deal_Scrapper
          chmod +x mvnw
          ./mvnw clean test